name: Build Docker and push to ECR
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout code from repo
        uses: actions/checkout@master
      - name: Build Docker and push to ECR
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: ops-aws-sigv4-proxy
          tag: ${{ github.run_id }}
          registry: 292130047527.dkr.ecr.ap-east-1.amazonaws.com
          # dockerfile: ../Dockerfile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
